/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-bright": "#353943",
        "on-primary": "#68001a",
        "secondary-fixed": "#ffd9dd",
        "on-tertiary-fixed": "#40000c",
        "on-tertiary-fixed-variant": "#8d102b",
        "surface-container-lowest": "#0a0e17",
        "primary-fixed": "#ffdada",
        "inverse-surface": "#dfe2ef",
        "outline": "#ad8789",
        "on-secondary-container": "#ff9cad",
        "secondary-fixed-dim": "#ffb2bd",
        "surface-tint": "#ffb3b6",
        "tertiary": "#ffb3b6",
        "error": "#ffb4ab",
        "on-secondary-fixed-variant": "#8c1038",
        "on-error-container": "#ffdad6",
        "surface-container-highest": "#31353f",
        "outline-variant": "#5d3f40",
        "on-error": "#690005",
        "on-primary-container": "#5b0015",
        "tertiary-container": "#f25f6e",
        "inverse-primary": "#be0037",
        "primary": "#ffb3b6",
        "secondary-container": "#8f133a",
        "surface-container": "#1c1f29",
        "inverse-on-surface": "#2c303a",
        "tertiary-fixed": "#ffdada",
        "on-surface-variant": "#e6bcbd",
        "on-secondary-fixed": "#400014",
        "surface-container-low": "#181b25",
        "tertiary-fixed-dim": "#ffb3b6",
        "on-tertiary": "#68001a",
        "surface-variant": "#31353f",
        "on-primary-fixed": "#40000c",
        "primary-container": "#ff2a55",
        "on-background": "#dfe2ef",
        "on-surface": "#dfe2ef",
        "surface-container-high": "#262a34",
        "background": "#0f131c",
        "surface": "#0f131c",
        "on-secondary": "#670025",
        "error-container": "#93000a",
        "primary-fixed-dim": "#ffb3b6",
        "surface-dim": "#0f131c",
        "on-tertiary-container": "#5b0015",
        "secondary": "#ffb2bd",
        "on-primary-fixed-variant": "#920028",
        "ruby-core": "#ff3366",
        "ruby-deep": "#800d23",
        "laser-glow": "rgba(255, 42, 85, 0.35)",
        "laser-crimson": "#ff2a55",
        "amber-warn": "#fbbf24",
        "border-subtle": "rgba(255, 255, 255, 0.08)",
        "border-crimson": "rgba(255, 42, 85, 0.4)"
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        full: "9999px"
      },
      spacing: {
        "space-xs": "0.25rem",
        "space-sm": "0.5rem",
        "space-md": "1rem",
        "space-lg": "1.5rem",
        "space-xl": "2.5rem",
        "margin-sm": "1rem",
        "margin": "2rem",
        "margin-lg": "4rem",
        gutter: "1.5rem",
        "gutter-sm": "1rem",
        "gutter-lg": "2rem"
      },
      fontFamily: {
        display: ["Plus Jakarta Sans", "sans-serif"],
        headline: ["Plus Jakarta Sans", "sans-serif"],
        body: ["Plus Jakarta Sans", "sans-serif"],
        mono: ["JetBrains Mono", "monospace"]
      }
    }
  },
  plugins: []
};
